#!/bin/sh
export XDG_RUNTIME_DIR=/run/user/1000

[ -r ./conf ] && . ./conf

if [ "${LOGGING_ENABLE}x" = "1x" -a -n "${LOG_LEVEL}" ]; then
    export PIPEWIRE_DEBUG="${LOG_LEVEL}"
fi

exec pipewire ${OPTS:-} 2>&1
