#!/bin/sh
export XDG_RUNTIME_DIR=/run/user/1000

# Wait for the PipeWire Media Session daemon to start.
sv check "$HOME/.local/runit/run/wireplumber" >/dev/null || exit 1

[ -r ./conf ] && . ./conf

if [ "${LOGGING_ENABLE}x" = "1x" -a -n "${LOG_LEVEL}" ]; then
    export PIPEWIRE_DEBUG="${LOG_LEVEL}"
fi

exec pipewire-pulse ${OPTS:-} 2>&1
